from __future__ import annotations


ARTIFACT_DIRS: tuple[dict[str, str], ...] = (
    {
        "path": "e11_condition_geometry",
        "role": "Source package for E11 problems, optimizers, diagnostics, reporting, and plotting.",
        "commit_policy": "commit",
    },
    {
        "path": "scripts",
        "role": "Experiment runners, artifact writers, and validation scripts.",
        "commit_policy": "commit E11 scripts",
    },
    {
        "path": "tests",
        "role": "Smoke tests, diagnostics tests, reporting tests, and validator guardrail tests.",
        "commit_policy": "commit",
    },
    {
        "path": "discussion",
        "role": "Generated head-to-tail paper evidence plus legacy condition-geometry guardrail notes.",
        "commit_policy": "commit",
    },
    {
        "path": "results",
        "role": "Generated CSV evidence used by the paper table, discussion artifacts, and validator.",
        "commit_policy": "commit current E11 evidence set",
    },
    {
        "path": "figures",
        "role": "Static figures used by the paper draft and paper-facing Markdown artifacts.",
        "commit_policy": "commit static E11 figures",
    },
    {
        "path": "configs",
        "role": "Experiment configuration snapshots.",
        "commit_policy": "commit",
    },
    {
        "path": "paper",
        "role": "Head-to-tail LaTeX paper draft, generated paper table, and experiment triage notes.",
        "commit_policy": "commit source and selected rendered PDFs",
    },
    {
        "path": "Makefile",
        "role": "Thin reproducibility entrypoint for E11 artifact generation and validation commands.",
        "commit_policy": "commit",
    },
    {
        "path": ".gitignore",
        "role": "Keeps local caches, datasets, and generated videos out of default commits.",
        "commit_policy": "commit",
    },
    {
        "path": ".gitattributes",
        "role": "Marks generated evidence artifacts and binary files for cleaner GitHub review.",
        "commit_policy": "commit",
    },
)


KEY_TABLES: tuple[str, ...] = (
    "results/e11/step_metrics.csv",
    "results/e11/activation_perturbation_summary.csv",
    "results/e11_head_tail_interference/step_metrics.csv",
    "results/e11_head_tail_interference/pair_summary.csv",
    "results/e11_long_tail_one_step/step_metrics.csv",
    "results/e11_long_tail_one_step/pair_summary.csv",
    "results/e11_long_tail_one_step/layer_metrics.csv",
    "results/e11_cifar100_lt_one_step/step_metrics.csv",
    "results/e11_cifar100_lt_one_step/pair_summary.csv",
    "results/e11_cifar100_lt_one_step/layer_metrics.csv",
    "results/e11_cifar100_resnet_one_step/step_metrics.csv",
    "results/e11_cifar100_resnet_one_step/pair_summary.csv",
    "results/e11_cifar100_resnet_one_step/layer_metrics.csv",
    "results/e11_cifar100_resnet_one_step_rho002/step_metrics.csv",
    "results/e11_cifar100_resnet_one_step_rho002/pair_summary.csv",
    "results/e11_cifar100_resnet_one_step_rho002/layer_metrics.csv",
    "results/e11_cifar100_resnet_checkpoint_sweep/step_metrics.csv",
    "results/e11_cifar100_resnet_checkpoint_sweep/pair_summary.csv",
    "results/e11_cifar100_resnet_checkpoint_sweep/layer_metrics.csv",
    "results/e11_cifar100_resnet_condition_proxy_scatter/scatter_points.csv",
    "results/e11_cifar100_resnet_condition_proxy_scatter/summary.csv",
    "results/e11_cifar100_resnet_condition_proxy_scatter/layer_summary.csv",
    "results/e11_cifar100_resnet_fc_condition_scatter/step_metrics.csv",
    "results/e11_cifar100_resnet_fc_condition_scatter/summary.csv",
    "results/e11_cifar100_resnet_fc_condition_scatter/condition_metrics.csv",
    "results/e11_cifar100_resnet_tail_quality_control/step_metrics.csv",
    "results/e11_cifar100_resnet_tail_quality_control/pair_summary.csv",
    "results/e11_cifar100_resnet_tail_quality_control/layer_metrics.csv",
    "results/e11_cifar100_resnet_layer_jvp_tail_quality/metrics.csv",
    "results/e11_cifar100_resnet_layer_jvp_tail_quality/paired_metrics.csv",
    "results/e11_cifar100_resnet_layer_jvp_tail_quality/summary.csv",
    "results/e11_cifar100_resnet_layer_jvp_tail_quality/overall_summary.csv",
    "results/e11_cifar100_resnet_layer_jvp_checkpoint_prediction/metrics.csv",
    "results/e11_cifar100_resnet_layer_jvp_checkpoint_prediction/paired_metrics.csv",
    "results/e11_cifar100_resnet_layer_jvp_checkpoint_prediction/layer_summary.csv",
    "results/e11_cifar100_resnet_layer_jvp_checkpoint_prediction/checkpoint_summary.csv",
    "results/e11_cifar100_resnet_layer_jvp_checkpoint_prediction/prediction_pairs.csv",
    "results/e11_cifar100_resnet_layer_jvp_checkpoint_prediction/prediction_summary.csv",
    "results/e11_cifar100_resnet_lt_standard_eval/train_trace.csv",
    "results/e11_cifar100_resnet_lt_standard_eval/class_metrics.csv",
    "results/e11_cifar100_resnet_lt_standard_eval/group_metrics.csv",
    "results/e11_cifar100_resnet_lt_standard_eval/summary.csv",
    "results/e11_cifar100_resnet_lt_standard_eval/class_summary.csv",
    "results/e11_cifar100_resnet_practical_muon_bridge/metrics.csv",
    "results/e11_cifar100_resnet_practical_muon_bridge/paired_metrics.csv",
    "results/e11_cifar100_resnet_practical_muon_bridge/summary.csv",
    "results/e11_cifar100_resnet_practical_muon_bridge/step_summary.csv",
    "results/e11_long_tail_imbalance_ablation/step_metrics.csv",
    "results/e11_long_tail_imbalance_ablation/summary.csv",
    "results/e11_long_tail_checkpoint_sweep/step_metrics.csv",
    "results/e11_long_tail_checkpoint_sweep/summary.csv",
    "results/e11_long_tail_class_partition_sweep/step_metrics.csv",
    "results/e11_long_tail_class_partition_sweep/summary.csv",
    "results/e11_long_tail_rho_sweep/step_metrics.csv",
    "results/e11_long_tail_rho_sweep/summary.csv",
    "results/e11_long_tail_muon_bridge/step_metrics.csv",
    "results/e11_long_tail_muon_bridge/pair_summary.csv",
    "results/e11_local_linearization/summary.csv",
    "results/e11_long_tail_practical_muon_bridge/step_metrics.csv",
    "results/e11_long_tail_practical_muon_bridge/step_summary.csv",
    "results/e11_long_tail_practical_muon_bridge/summary.csv",
    "results/e11_long_tail_muon_state_source_control/step_metrics.csv",
    "results/e11_long_tail_muon_state_source_control/summary.csv",
    "results/e11_long_tail_practical_training/step_metrics.csv",
    "results/e11_long_tail_practical_training/summary.csv",
    "results/e11_long_tail_practical_training_lr_sweep/sweep_summary.csv",
    "results/e11_long_tail_forgetting/step_metrics.csv",
    "results/e11_long_tail_forgetting/summary.csv",
    "results/e11_long_tail_layerwise/metrics.csv",
    "results/e11_long_tail_layerwise/summary.csv",
    "results/e11_equal_update/step_metrics.csv",
    "results/e11_equal_update/activation_perturbation_summary.csv",
    "results/e11_overlap_followup/step_metrics.csv",
    "results/e11_hyperparam_sweep/equal_step_metrics.csv",
    "results/e11_target_update_sweep/step_metrics.csv",
    "results/e11_mlp_width_sweep/step_metrics.csv",
    "results/e11_mlp_per_layer_control/step_metrics.csv",
    "results/e11_mlp_layer_hybrid/step_metrics.csv",
    "results/e11_mnist_mlp_probe/step_metrics.csv",
    "results/e11_deep_mnist_mlp_probe/step_metrics.csv",
    "results/e11_mnist_patch_probe/step_metrics.csv",
    "results/e11_mnist_conv_probe/step_metrics.csv",
    "results/e11_stateless_direction_ablation/stateless_direction_rows.csv",
    "results/e11_stateless_optimizer_trajectory/stateless_optimizer_step_metrics.csv",
    "results/e11_spectral_allocation_probe/probe_rows.csv",
    "results/e11_singular_vector_trajectory/update_subspace_rows.csv",
    "results/e11_singular_vector_swap_probe/swap_probe_rows.csv",
    "results/e11_natural_update_swap_probe/natural_update_swap_rows.csv",
    "results/e11_optimizer_switch_probe/optimizer_switch_rows.csv",
    "results/e11_optimizer_switch_reset_control/optimizer_switch_reset_rows.csv",
    "results/e11_optimizer_switch_horizon_sweep/optimizer_switch_horizon_rows.csv",
    "results/e11_optimizer_switch_lr_sweep/optimizer_switch_lr_rows.csv",
    "results/e11_boundary_predictor/boundary_predictor_rows.csv",
    "results/e11_mechanism_boundary/mechanism_boundary_map.csv",
    "results/e11_cross_task_signature/cross_task_signature_summary.csv",
    "results/e11_boundary_predictor/boundary_predictor_uncertainty.csv",
    "results/e11_head_tail_alignment_ablation/step_metrics.csv",
    "results/e11_head_tail_alignment_ablation/summary.csv",
)


KEY_DOCUMENTS: tuple[str, ...] = (
    "README_E11.md",
    "discussion/e11_paper_skeleton.md",
    "discussion/e11_main_paper_package.md",
    "discussion/e11_main_figure_captions.md",
    "discussion/e11_notation_glossary.md",
    "discussion/e11_quantitative_claim_ledger.md",
    "discussion/e11_reproduction_checklist.md",
    "discussion/e11_reviewer_risk_audit.md",
    "discussion/e11_pasted_review_audit.md",
    "discussion/e11_completion_audit.md",
    "discussion/e11_end_of_draft_self_review.md",
    "discussion/e11_reference_audit.md",
    "discussion/e11_paper_readiness_audit.md",
    "discussion/e11_top_conference_plan.md",
    "discussion/e11_evidence_index.md",
    "discussion/e11_research_synthesis.md",
    "discussion/e11_research_direction_map.md",
    "discussion/e11_claim_validity_audit.md",
    "discussion/e11_cifar100_lt_one_step.md",
    "discussion/e11_cifar100_resnet_one_step.md",
    "discussion/e11_cifar100_resnet_one_step_rho002.md",
    "discussion/e11_cifar100_resnet_checkpoint_sweep.md",
    "discussion/e11_cifar100_resnet_condition_proxy_scatter.md",
    "discussion/e11_cifar100_resnet_fc_condition_scatter.md",
    "discussion/e11_cifar100_resnet_tail_quality_control.md",
    "discussion/e11_cifar100_resnet_layer_jvp_tail_quality.md",
    "discussion/e11_cifar100_resnet_layer_jvp_checkpoint_prediction.md",
    "discussion/e11_cifar100_resnet_lt_standard_eval.md",
    "discussion/e11_cifar100_resnet_practical_muon_bridge.md",
)


IGNORE_POLICY: tuple[dict[str, str], ...] = (
    {
        "path_or_pattern": "data/",
        "reason": "Local torchvision dataset cache; downloaded by MNIST/CIFAR probes and not part of the evidence set.",
    },
    {
        "path_or_pattern": "outputs/",
        "reason": "Local Slurm stdout/stderr logs; final CSV/Markdown/figure artifacts are committed separately.",
    },
    {
        "path_or_pattern": ".pytest_cache/",
        "reason": "Local test runner cache.",
    },
    {
        "path_or_pattern": "*.gif, *.mp4",
        "reason": "Generated animations/videos are not part of the default E11 evidence set; force-add only when explicitly needed.",
    },
    {
        "path_or_pattern": "slidev/",
        "reason": "Local presentation workspace, intentionally excluded from the repo.",
    },
)


MAIN_RESULT_SCRIPTS: tuple[str, ...] = (
    "scripts/e11_run_experiments.py",
    "scripts/e11_make_figures.py",
    "scripts/e11_run_equal_update_control.py",
    "scripts/e11_run_head_tail_interference.py",
    "scripts/e11_run_head_tail_alignment_ablation.py",
    "scripts/e11_run_long_tail_one_step.py",
    "scripts/e11_run_cifar100_lt_one_step.py",
    "scripts/e11_run_cifar100_resnet_one_step.py",
    "scripts/e11_run_cifar100_resnet_checkpoint_sweep.py",
    "scripts/e11_run_cifar100_resnet_condition_proxy_scatter.py",
    "scripts/e11_run_cifar100_resnet_fc_condition_scatter.py",
    "scripts/e11_run_cifar100_resnet_layer_jvp_tail_quality.py",
    "scripts/e11_run_cifar100_resnet_layer_jvp_checkpoint_prediction.py",
    "scripts/e11_run_cifar100_resnet_lt_standard_eval.py",
    "scripts/e11_run_cifar100_resnet_practical_muon_bridge.py",
    "scripts/e11_run_long_tail_imbalance_ablation.py",
    "scripts/e11_run_long_tail_checkpoint_sweep.py",
    "scripts/e11_run_long_tail_class_partition_sweep.py",
    "scripts/e11_run_long_tail_rho_sweep.py",
    "scripts/e11_run_long_tail_muon_bridge.py",
    "scripts/e11_run_long_tail_practical_muon_bridge.py",
    "scripts/e11_run_long_tail_muon_state_source_control.py",
    "scripts/e11_run_long_tail_practical_training.py",
    "scripts/e11_run_long_tail_practical_training_lr_sweep.py",
    "scripts/e11_run_long_tail_forgetting.py",
    "scripts/e11_run_long_tail_layerwise.py",
    "scripts/e11_run_spectral_allocation_probe.py",
)


MAIN_EVIDENCE_STAGES: tuple[dict[str, str], ...] = (
    {
        "stage": "Core trajectories",
        "command": "python3 scripts/e11_run_experiments.py",
        "produces": "results/e11/*",
        "paper_role": "Base Adam/Muon trajectories and raw diagnostics.",
    },
    {
        "stage": "Core figures",
        "command": "python3 scripts/e11_make_figures.py",
        "produces": "figures/e11/*",
        "paper_role": "Static diagnostic figures for the base run.",
    },
    {
        "stage": "Matched-update control",
        "command": "python3 scripts/e11_run_equal_update_control.py",
        "produces": "results/e11_equal_update/* and figures/e11_equal_update/*",
        "paper_role": "Background E11 optimizer-geometry control; not a current head-to-tail main figure.",
    },
    {
        "stage": "Head-to-tail interference probe",
        "command": "python3 scripts/e11_run_head_tail_interference.py",
        "produces": "results/e11_head_tail_interference/* and figures/e11_head_tail_interference/*",
        "paper_role": "Synthetic matched-head-gain evidence for the head-to-tail interference condition.",
    },
    {
        "stage": "Head-to-tail singular-vector alignment ablation",
        "command": "python3 scripts/e11_run_head_tail_alignment_ablation.py",
        "produces": "results/e11_head_tail_alignment_ablation/* and figures/e11_head_tail_alignment_ablation/*",
        "paper_role": "Checks that the sandwich rank condition is a worst-case bound-ordering condition rather than a realized-drift predictor by itself.",
    },
    {
        "stage": "Long-tailed one-step diagnostic",
        "command": "python3 scripts/e11_run_long_tail_one_step.py",
        "produces": "results/e11_long_tail_one_step/* and figures/e11_long_tail_one_step/*",
        "paper_role": "Real-data matched-head-gain check on held-out tail examples.",
    },
    {
        "stage": "CIFAR-100-LT MLP one-step diagnostic",
        "command": "python3 scripts/e11_run_cifar100_lt_one_step.py --device cpu --no-download",
        "produces": "results/e11_cifar100_lt_one_step/* and figures/e11_cifar100_lt_one_step/*",
        "paper_role": "Larger visual-data matched-head-gain check using an exactly controlled two-matrix MLP intervention.",
    },
    {
        "stage": "CIFAR-100-LT ResNet18 one-step diagnostic",
        "command": "sbatch scripts/slurm/e11_cifar100_resnet_one_step.sbatch",
        "produces": "results/e11_cifar100_resnet_one_step/* and figures/e11_cifar100_resnet_one_step/*",
        "paper_role": "GPU ResNet18 architecture robustness check for matched-head-gain tail drift at target head gain 0.005 times head loss.",
    },
    {
        "stage": "CIFAR-100-LT ResNet18 smaller-head-gain check",
        "command": "sbatch scripts/slurm/e11_cifar100_resnet_one_step_rho002.sbatch",
        "produces": "results/e11_cifar100_resnet_one_step_rho002/* and figures/e11_cifar100_resnet_one_step_rho002/*",
        "paper_role": "Target-head-gain scale robustness check for the CIFAR-100-LT ResNet18 diagnostic at 0.002 times head loss.",
    },
    {
        "stage": "CIFAR-100-LT ResNet18 checkpoint-quality sweep",
        "command": "sbatch scripts/slurm/e11_cifar100_resnet_checkpoint_sweep.sbatch",
        "produces": "results/e11_cifar100_resnet_checkpoint_sweep/* and figures/e11_cifar100_resnet_checkpoint_sweep/*",
        "paper_role": "GPU checkpoint sweep across 250, 500, 1000, and 2000 warmup steps; strengthens single-checkpoint robustness while preserving the weak-tail-predictor caveat.",
    },
    {
        "stage": "CIFAR-100-LT ResNet18 condition-proxy scatter",
        "command": "python3 scripts/e11_run_cifar100_resnet_condition_proxy_scatter.py",
        "produces": "results/e11_cifar100_resnet_condition_proxy_scatter/* and figures/e11_cifar100_resnet_condition_proxy_scatter/*",
        "paper_role": "Natural-task rank-side proxy scatter showing that head-gradient rank alone is not the full downstream-aware condition.",
    },
    {
        "stage": "CIFAR-100-LT ResNet18 final-layer condition scatter",
        "command": "sbatch scripts/slurm/e11_cifar100_resnet_fc_condition_scatter.sbatch",
        "produces": "results/e11_cifar100_resnet_fc_condition_scatter/* and figures/e11_cifar100_resnet_fc_condition_scatter/*",
        "paper_role": "Final-layer downstream-aware condition diagnostic measuring nrank(G_H) against tail feature stable rank at matched head gain.",
    },
    {
        "stage": "CIFAR-100 ResNet18 tail-quality control",
        "command": "sbatch scripts/slurm/e11_cifar100_resnet_tail_quality_control.sbatch",
        "produces": "results/e11_cifar100_resnet_tail_quality_control/* and figures/e11_cifar100_resnet_tail_quality_control/*",
        "paper_role": "Tail-rich ResNet18 checkpoint control testing whether lower matched-gain drift persists when pre-update tail accuracy is meaningfully above the weak-tail checkpoint sweep.",
    },
    {
        "stage": "CIFAR-100-LT ResNet18 all-layer JVP tail-quality diagnostic",
        "command": "sbatch scripts/slurm/e11_cifar100_resnet_layer_jvp_tail_quality.sbatch",
        "produces": "results/e11_cifar100_resnet_layer_jvp_tail_quality/* and figures/e11_cifar100_resnet_layer_jvp_tail_quality/*",
        "paper_role": "All Conv/Linear layer finite-difference tail-sensitivity check at the tail-rich ResNet checkpoint; reports unit JVP, matched-gain scaled JVP, and observed layer-only drift.",
    },
    {
        "stage": "CIFAR-100-LT ResNet18 all-layer JVP checkpoint-transfer benchmark",
        "command": "sbatch scripts/slurm/e11_cifar100_resnet_layer_jvp_checkpoint_prediction.sbatch",
        "produces": "results/e11_cifar100_resnet_layer_jvp_checkpoint_prediction/* and figures/e11_cifar100_resnet_layer_jvp_checkpoint_prediction/*",
        "paper_role": "Held-out checkpoint-transfer boundary check for whether all-layer downstream-aware JVP quantities predict observed layer risk across tail-rich ResNet checkpoints.",
    },
    {
        "stage": "CIFAR-100-LT ResNet18 standard many/medium/few reporting baseline",
        "command": "sbatch scripts/slurm/e11_cifar100_resnet_lt_standard_eval.sbatch",
        "produces": "results/e11_cifar100_resnet_lt_standard_eval/* and figures/e11_cifar100_resnet_lt_standard_eval/*",
        "paper_role": "Standard long-tail IF=100 ResNet18 reporting surface for many/medium/few balanced accuracy; not a tuned optimizer benchmark.",
    },
    {
        "stage": "CIFAR-100-LT ResNet18 practical Muon trajectory bridge",
        "command": "sbatch scripts/slurm/e11_cifar100_resnet_practical_muon_bridge.sbatch",
        "produces": "results/e11_cifar100_resnet_practical_muon_bridge/* and figures/e11_cifar100_resnet_practical_muon_bridge/*",
        "paper_role": "GPU ResNet18 state-trajectory compatibility check for exact polar and finite Newton-Schulz Muon-style momentum directions on AdamW- and NS-Muon-sampled matrix-weight states.",
    },
    {
        "stage": "Long-tailed imbalance ablation",
        "command": "python3 scripts/e11_run_long_tail_imbalance_ablation.py",
        "produces": "results/e11_long_tail_imbalance_ablation/* and figures/e11_long_tail_imbalance_ablation/*",
        "paper_role": "Checks whether the one-step tail-drift pattern persists as the tail training split becomes rarer.",
    },
    {
        "stage": "Long-tailed checkpoint sweep",
        "command": "python3 scripts/e11_run_long_tail_checkpoint_sweep.py",
        "produces": "results/e11_long_tail_checkpoint_sweep/* and figures/e11_long_tail_checkpoint_sweep/*",
        "paper_role": "Checks whether the one-step tail-drift pattern depends on selecting a single warmup checkpoint.",
    },
    {
        "stage": "Long-tailed class-partition sweep",
        "command": "python3 scripts/e11_run_long_tail_class_partition_sweep.py",
        "produces": "results/e11_long_tail_class_partition_sweep/* and figures/e11_long_tail_class_partition_sweep/*",
        "paper_role": "Checks whether the one-step tail-drift pattern depends on the default head/tail digit-class partition.",
    },
    {
        "stage": "Long-tailed matched-gain rho sweep",
        "command": "python3 scripts/e11_run_long_tail_rho_sweep.py",
        "produces": "results/e11_long_tail_rho_sweep/* and figures/e11_long_tail_rho_sweep/*",
        "paper_role": "Checks whether the one-step tail-drift pattern depends on the default target head-gain fraction.",
    },
    {
        "stage": "Long-tailed Muon-style compatibility diagnostic",
        "command": "python3 scripts/e11_run_long_tail_muon_bridge.py",
        "produces": "results/e11_long_tail_muon_bridge/* and figures/e11_long_tail_muon_bridge/*",
        "paper_role": "Fixed-checkpoint compatibility check from ideal polar(G_t) to momentum polar(M_t) and Newton-Schulz Muon-style directions.",
    },
    {
        "stage": "Long-tailed practical-Muon trajectory compatibility",
        "command": "python3 scripts/e11_run_long_tail_practical_muon_bridge.py",
        "produces": "results/e11_long_tail_practical_muon_bridge/* and figures/e11_long_tail_practical_muon_bridge/*",
        "paper_role": "Short trajectory-level check of momentum and Newton-Schulz Muon-style directions at sampled states.",
    },
    {
        "stage": "Long-tailed Muon state-source control",
        "command": "python3 scripts/e11_run_long_tail_muon_state_source_control.py",
        "produces": "results/e11_long_tail_muon_state_source_control/* and figures/e11_long_tail_muon_state_source_control/*",
        "paper_role": "Checks whether Muon-style direction compatibility persists when sampled states come from a Fro/GD-style trajectory rather than an NS-Muon-style trajectory.",
    },
    {
        "stage": "Long-tailed practical training diagnostic",
        "command": "python3 scripts/e11_run_long_tail_practical_training.py",
        "produces": "results/e11_long_tail_practical_training/* and figures/e11_long_tail_practical_training/*",
        "paper_role": "Practical Adam-vs-NS-Muon-style imbalanced mini-batch training sanity check with final tail metrics.",
    },
    {
        "stage": "Long-tailed practical training LR sensitivity",
        "command": "python3 scripts/e11_run_long_tail_practical_training_lr_sweep.py",
        "produces": "results/e11_long_tail_practical_training_lr_sweep/* and figures/e11_long_tail_practical_training_lr_sweep/*",
        "paper_role": "Learning-rate sensitivity check for the practical NS-Muon-style training diagnostic.",
    },
    {
        "stage": "Head-only forgetting probe",
        "command": "python3 scripts/e11_run_long_tail_forgetting.py",
        "produces": "results/e11_long_tail_forgetting/* and figures/e11_long_tail_forgetting/*",
        "paper_role": "Short-horizon held-out tail drift under matched head-only update schedules.",
    },
    {
        "stage": "Long-tailed layerwise diagnostic",
        "command": "python3 scripts/e11_run_long_tail_layerwise.py",
        "produces": "results/e11_long_tail_layerwise/* and figures/e11_long_tail_layerwise/*",
        "paper_role": "Layerwise finite-difference tail JVP and matched-head-gain drift evidence.",
    },
    {
        "stage": "Spectral allocation probe",
        "command": "python3 scripts/e11_run_spectral_allocation_probe.py",
        "produces": "results/e11_spectral_allocation_probe/* and figures/e11_spectral_allocation_probe/*",
        "paper_role": "Mechanism background for norm-budget geometry; appendix evidence for the current head-to-tail paper.",
    },
    {
        "stage": "Mechanism boundary map",
        "command": "python3 scripts/e11_write_mechanism_boundary.py",
        "produces": "results/e11_mechanism_boundary/mechanism_boundary_map.csv",
        "paper_role": "Legacy E11 boundary summary used as background, not the current head-to-tail result table.",
    },
)


APPENDIX_RUNNER_SCRIPTS: tuple[str, ...] = (
    "scripts/e11_run_overlap_followup.py",
    "scripts/e11_run_hyperparam_sweep.py",
    "scripts/e11_run_target_update_sweep.py",
    "scripts/e11_run_mlp_width_sweep.py",
    "scripts/e11_run_mlp_per_layer_control.py",
    "scripts/e11_run_mlp_layer_hybrid.py",
    "scripts/e11_run_mnist_mlp_probe.py",
    "scripts/e11_run_deep_mnist_mlp_probe.py",
    "scripts/e11_run_mnist_patch_probe.py",
    "scripts/e11_run_mnist_conv_probe.py",
    "scripts/e11_run_stateless_direction_ablation.py",
    "scripts/e11_run_stateless_optimizer_trajectory.py",
    "scripts/e11_run_singular_vector_trajectory.py",
    "scripts/e11_run_singular_vector_swap_probe.py",
    "scripts/e11_run_natural_update_swap_probe.py",
    "scripts/e11_run_optimizer_switch_probe.py",
    "scripts/e11_run_optimizer_switch_reset_control.py",
    "scripts/e11_run_optimizer_switch_horizon_sweep.py",
    "scripts/e11_run_optimizer_switch_lr_sweep.py",
    "scripts/e11_run_boundary_predictor.py",
)


APPENDIX_RUNNER_DESCRIPTIONS: dict[str, str] = {
    "scripts/e11_run_overlap_followup.py": "Focused overlap settings used by early boundary and guardrail claims.",
    "scripts/e11_run_hyperparam_sweep.py": "Learning-rate sensitivity and best-over-LR guardrail.",
    "scripts/e11_run_target_update_sweep.py": "Target update-size boundary control.",
    "scripts/e11_run_mlp_width_sweep.py": "MLP width boundary and transition control.",
    "scripts/e11_run_mlp_per_layer_control.py": "Per-layer matched-update boundary control.",
    "scripts/e11_run_mlp_layer_hybrid.py": "Layerwise optimizer hybrid control for MLP update allocation.",
    "scripts/e11_run_mnist_mlp_probe.py": "Small neural sanity benchmark.",
    "scripts/e11_run_deep_mnist_mlp_probe.py": "Deeper all-matrix MNIST sanity benchmark.",
    "scripts/e11_run_mnist_patch_probe.py": "Matrix-only MNIST patch classifier sanity benchmark.",
    "scripts/e11_run_mnist_conv_probe.py": "Small true Conv2d MNIST sanity benchmark with flattened-kernel Muon view.",
    "scripts/e11_run_stateless_direction_ablation.py": "One-step stateless direction mechanism control.",
    "scripts/e11_run_stateless_optimizer_trajectory.py": "Short stateless trajectory mechanism control.",
    "scripts/e11_run_singular_vector_trajectory.py": "Gradient/update singular-vector overlap trajectory diagnostic.",
    "scripts/e11_run_singular_vector_swap_probe.py": "Singular-vector swap mechanism control.",
    "scripts/e11_run_natural_update_swap_probe.py": "Natural update-vector and singular geometry control.",
    "scripts/e11_run_optimizer_switch_probe.py": "Optimizer-state continuation probe.",
    "scripts/e11_run_optimizer_switch_reset_control.py": "Reset-state control for optimizer switching.",
    "scripts/e11_run_optimizer_switch_horizon_sweep.py": "Continuation horizon sensitivity control.",
    "scripts/e11_run_optimizer_switch_lr_sweep.py": "Continuation negative control against long-horizon overclaiming.",
    "scripts/e11_run_boundary_predictor.py": "Leave-setting-out predictive-boundary baseline.",
}


PAPER_ASSET_SCRIPTS: tuple[str, ...] = (
    "scripts/e11_write_discussion_outline.py",
    "scripts/e11_write_head_tail_interference_note.py",
    "scripts/e11_write_head_tail_alignment_ablation_note.py",
    "scripts/e11_write_long_tail_one_step_note.py",
    "scripts/e11_write_long_tail_imbalance_ablation_note.py",
    "scripts/e11_write_long_tail_checkpoint_sweep_note.py",
    "scripts/e11_write_long_tail_class_partition_sweep_note.py",
    "scripts/e11_write_long_tail_rho_sweep_note.py",
    "scripts/e11_write_long_tail_muon_bridge_note.py",
    "scripts/e11_write_long_tail_practical_muon_bridge_note.py",
    "scripts/e11_write_long_tail_muon_state_source_control_note.py",
    "scripts/e11_write_long_tail_practical_training_note.py",
    "scripts/e11_write_long_tail_practical_training_lr_sweep_note.py",
    "scripts/e11_write_long_tail_forgetting_note.py",
    "scripts/e11_write_long_tail_layerwise_note.py",
    "scripts/e11_write_head_tail_paper_results.py",
    "scripts/e11_write_local_linearization_table.py",
    "scripts/e11_write_claim_audit.py",
    "scripts/e11_write_evidence_index.py",
    "scripts/e11_write_research_synthesis.py",
    "scripts/e11_write_research_direction_map.py",
    "scripts/e11_write_paper_readiness_audit.py",
    "scripts/e11_write_paper_skeleton.py",
    "scripts/e11_write_main_paper_package.py",
    "scripts/e11_write_main_figure_captions.py",
    "scripts/e11_write_notation_glossary.py",
    "scripts/e11_write_quantitative_claim_ledger.py",
    "scripts/e11_write_paper_numbers.py",
    "scripts/e11_write_paper_figures.py",
    "scripts/e11_write_reproduction_checklist.py",
    "scripts/e11_write_reviewer_risk_audit.py",
    "scripts/e11_write_artifact_manifest.py",
)


LEGACY_GUARDRAIL_SCRIPTS: tuple[str, ...] = (
    "scripts/e11_write_activation_perturbation_note.py",
    "scripts/e11_write_mechanism_ladder.py",
    "scripts/e11_write_cross_task_signature.py",
    "scripts/e11_write_mechanism_boundary.py",
    "scripts/e11_write_theory_note.py",
    "scripts/e11_write_mechanism_theorem_bridge.py",
    "scripts/e11_write_boundary_predictor_audit.py",
    "scripts/e11_write_optimizer_ablation_map.py",
    "scripts/e11_write_optimizer_invariance_audit.py",
)
