from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from e11_condition_geometry.reporting import fmt


DISCUSSION_OUTPUT_PATH = Path("discussion/e11_paper_numbers.tex")
PAPER_OUTPUT_PATH = Path("paper/specgrad_activation_paper/tables/e11_paper_numbers.tex")


def macro(name: str, value: object) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def ci_text(row: pd.Series, low: str, high: str) -> str:
    return f"[{fmt(row[low])}, {fmt(row[high])}]"


def ci_macros(prefix: str, row: pd.Series, low: str, high: str) -> list[str]:
    return [
        macro(f"{prefix}CiLow", fmt(row[low])),
        macro(f"{prefix}CiHigh", fmt(row[high])),
        macro(f"{prefix}Ci", ci_text(row, low, high)),
    ]


def main() -> None:
    head_tail = pd.read_csv("results/e11_head_tail_interference/pair_summary.csv").set_index("setting")
    one_step = pd.read_csv("results/e11_long_tail_one_step/pair_summary.csv").iloc[0]
    muon_bridge = pd.read_csv("results/e11_long_tail_muon_bridge/pair_summary.csv").set_index("direction")
    practical_bridge = pd.read_csv("results/e11_long_tail_practical_muon_bridge/summary.csv").set_index("direction")
    practical_training = pd.read_csv("results/e11_long_tail_practical_training/summary.csv").iloc[0]
    practical_lr_sweep = pd.read_csv("results/e11_long_tail_practical_training_lr_sweep/sweep_summary.csv")
    forgetting = pd.read_csv("results/e11_long_tail_forgetting/summary.csv").iloc[0]
    layerwise = pd.read_csv("results/e11_long_tail_layerwise/summary.csv")

    positive = head_tail.loc["high_head_rank_low_tail_srank"]
    negative = head_tail.loc["low_head_rank_high_tail_srank"]
    layer_one = layerwise[layerwise["layer"].eq(1)].iloc[0]
    layer_two = layerwise[layerwise["layer"].eq(2)].iloc[0]
    lr_0003 = practical_lr_sweep[practical_lr_sweep["muon_lr"].round(3).eq(0.003)].iloc[0]
    lr_001 = practical_lr_sweep[practical_lr_sweep["muon_lr"].round(3).eq(0.010)].iloc[0]
    lr_01 = practical_lr_sweep[practical_lr_sweep["muon_lr"].round(3).eq(0.100)].iloc[0]

    lines = [
        "% Auto-generated by scripts/e11_write_paper_numbers.py.",
        "% Do not edit by hand; regenerate after updating results.",
        "% Scope: current head-to-tail interference paper numbers only.",
        "",
        "% Synthetic head-to-tail boundary",
        macro("EelevenHeadTailPositiveNrankG", fmt(positive["mean_head_gradient_nuclear_rank"])),
        macro("EelevenHeadTailPositiveSsrankBTA", fmt(positive["mean_tail_downstream_aware_stable_rank"])),
        macro(
            "EelevenHeadTailPositiveDriftRatio",
            fmt(positive["geomean_tail_output_drift_sq_ratio_spectral_over_fro"]),
        ),
        *ci_macros(
            "EelevenHeadTailPositiveDriftRatio",
            positive,
            "tail_output_drift_sq_ratio_ci95_low",
            "tail_output_drift_sq_ratio_ci95_high",
        ),
        macro("EelevenHeadTailNegativeNrankG", fmt(negative["mean_head_gradient_nuclear_rank"])),
        macro("EelevenHeadTailNegativeSsrankBTA", fmt(negative["mean_tail_downstream_aware_stable_rank"])),
        macro(
            "EelevenHeadTailNegativeDriftRatio",
            fmt(negative["geomean_tail_output_drift_sq_ratio_spectral_over_fro"]),
        ),
        *ci_macros(
            "EelevenHeadTailNegativeDriftRatio",
            negative,
            "tail_output_drift_sq_ratio_ci95_low",
            "tail_output_drift_sq_ratio_ci95_high",
        ),
        "",
        "% Long-tailed one-step diagnostic",
        macro("EelevenLongTailOneStepSeeds", int(one_step["seeds"])),
        macro(
            "EelevenLongTailOneStepDriftRatio",
            fmt(one_step["geomean_tail_output_drift_sq_ratio_spectral_over_fro"]),
        ),
        *ci_macros(
            "EelevenLongTailOneStepDriftRatio",
            one_step,
            "tail_output_drift_sq_ratio_ci95_low",
            "tail_output_drift_sq_ratio_ci95_high",
        ),
        macro(
            "EelevenLongTailOneStepSpectralLowerFraction",
            fmt(one_step["spectral_less_tail_output_drift_fraction"]),
        ),
        macro(
            "EelevenLongTailOneStepTailLossDiff",
            fmt(one_step["mean_tail_loss_increase_diff_spectral_minus_fro"]),
        ),
        *ci_macros(
            "EelevenLongTailOneStepTailLossDiff",
            one_step,
            "tail_loss_increase_diff_ci95_low",
            "tail_loss_increase_diff_ci95_high",
        ),
        macro(
            "EelevenLongTailOneStepTailMarginDropDiff",
            fmt(one_step["mean_tail_margin_drop_diff_spectral_minus_fro"]),
        ),
        *ci_macros(
            "EelevenLongTailOneStepTailMarginDropDiff",
            one_step,
            "tail_margin_drop_diff_ci95_low",
            "tail_margin_drop_diff_ci95_high",
        ),
        macro(
            "EelevenLongTailOneStepTailAccuracyDropDiff",
            fmt(one_step["mean_tail_accuracy_drop_diff_spectral_minus_fro"]),
        ),
        *ci_macros(
            "EelevenLongTailOneStepTailAccuracyDropDiff",
            one_step,
            "tail_accuracy_drop_diff_ci95_low",
            "tail_accuracy_drop_diff_ci95_high",
        ),
        "",
        "% Long-tailed Muon-style compatibility diagnostic",
        macro(
            "EelevenLongTailMuonBridgePolarMomentumDriftRatio",
            fmt(muon_bridge.loc["polar_momentum", "geomean_tail_output_drift_sq_ratio_vs_fro"]),
        ),
        *ci_macros(
            "EelevenLongTailMuonBridgePolarMomentumDriftRatio",
            muon_bridge.loc["polar_momentum"],
            "tail_output_drift_sq_ratio_vs_fro_ci95_low",
            "tail_output_drift_sq_ratio_vs_fro_ci95_high",
        ),
        macro(
            "EelevenLongTailMuonBridgeNsMomentumDriftRatio",
            fmt(muon_bridge.loc["ns_momentum", "geomean_tail_output_drift_sq_ratio_vs_fro"]),
        ),
        *ci_macros(
            "EelevenLongTailMuonBridgeNsMomentumDriftRatio",
            muon_bridge.loc["ns_momentum"],
            "tail_output_drift_sq_ratio_vs_fro_ci95_low",
            "tail_output_drift_sq_ratio_vs_fro_ci95_high",
        ),
        macro(
            "EelevenLongTailMuonBridgePolarMomentumCosine",
            fmt(muon_bridge.loc["polar_momentum", "mean_direction_cosine_to_polar_grad"]),
        ),
        *ci_macros(
            "EelevenLongTailMuonBridgePolarMomentumCosine",
            muon_bridge.loc["polar_momentum"],
            "direction_cosine_to_polar_grad_ci95_low",
            "direction_cosine_to_polar_grad_ci95_high",
        ),
        "",
        "% Long-tailed practical Muon trajectory compatibility diagnostic",
        macro(
            "EelevenLongTailPracticalMuonBridgeComparisons",
            int(practical_bridge.loc["polar_momentum", "comparisons"]),
        ),
        macro(
            "EelevenLongTailPracticalMuonBridgePolarMomentumDriftRatio",
            fmt(practical_bridge.loc["polar_momentum", "geomean_tail_output_drift_sq_ratio_vs_fro"]),
        ),
        *ci_macros(
            "EelevenLongTailPracticalMuonBridgePolarMomentumDriftRatio",
            practical_bridge.loc["polar_momentum"],
            "tail_output_drift_sq_ratio_vs_fro_ci95_low",
            "tail_output_drift_sq_ratio_vs_fro_ci95_high",
        ),
        macro(
            "EelevenLongTailPracticalMuonBridgeNsMomentumDriftRatio",
            fmt(practical_bridge.loc["ns_momentum", "geomean_tail_output_drift_sq_ratio_vs_fro"]),
        ),
        *ci_macros(
            "EelevenLongTailPracticalMuonBridgeNsMomentumDriftRatio",
            practical_bridge.loc["ns_momentum"],
            "tail_output_drift_sq_ratio_vs_fro_ci95_low",
            "tail_output_drift_sq_ratio_vs_fro_ci95_high",
        ),
        macro(
            "EelevenLongTailPracticalMuonBridgeMomentumCosine",
            fmt(practical_bridge.loc["ns_momentum", "mean_gradient_momentum_cosine"]),
        ),
        *ci_macros(
            "EelevenLongTailPracticalMuonBridgeMomentumCosine",
            practical_bridge.loc["ns_momentum"],
            "gradient_momentum_cosine_ci95_low",
            "gradient_momentum_cosine_ci95_high",
        ),
        "",
        "% Long-tailed practical training diagnostic",
        macro("EelevenLongTailPracticalTrainingSeeds", int(practical_training["seeds"])),
        macro("EelevenLongTailPracticalTrainingSteps", int(practical_training["train_steps"])),
        macro("EelevenLongTailPracticalTrainingAdamLr", fmt(practical_training["adam_lr"])),
        macro("EelevenLongTailPracticalTrainingMuonLr", fmt(practical_training["muon_lr"])),
        macro(
            "EelevenLongTailPracticalTrainingTrainLossRatio",
            fmt(practical_training["geomean_final_train_loss_ratio_muon_over_adam"]),
        ),
        *ci_macros(
            "EelevenLongTailPracticalTrainingTrainLossRatio",
            practical_training,
            "final_train_loss_ratio_ci95_low",
            "final_train_loss_ratio_ci95_high",
        ),
        macro(
            "EelevenLongTailPracticalTrainingHeadLossRatio",
            fmt(practical_training["geomean_final_head_loss_ratio_muon_over_adam"]),
        ),
        *ci_macros(
            "EelevenLongTailPracticalTrainingHeadLossRatio",
            practical_training,
            "final_head_loss_ratio_ci95_low",
            "final_head_loss_ratio_ci95_high",
        ),
        macro(
            "EelevenLongTailPracticalTrainingTailLossRatio",
            fmt(practical_training["geomean_final_tail_eval_loss_ratio_muon_over_adam"]),
        ),
        *ci_macros(
            "EelevenLongTailPracticalTrainingTailLossRatio",
            practical_training,
            "final_tail_eval_loss_ratio_ci95_low",
            "final_tail_eval_loss_ratio_ci95_high",
        ),
        macro(
            "EelevenLongTailPracticalTrainingTailDriftRmsRatio",
            fmt(practical_training["geomean_final_tail_eval_drift_rms_ratio_muon_over_adam"]),
        ),
        *ci_macros(
            "EelevenLongTailPracticalTrainingTailDriftRmsRatio",
            practical_training,
            "final_tail_eval_drift_rms_ratio_ci95_low",
            "final_tail_eval_drift_rms_ratio_ci95_high",
        ),
        macro(
            "EelevenLongTailPracticalTrainingTailMarginDiff",
            fmt(practical_training["mean_final_tail_eval_margin_diff_muon_minus_adam"]),
        ),
        *ci_macros(
            "EelevenLongTailPracticalTrainingTailMarginDiff",
            practical_training,
            "final_tail_eval_margin_diff_ci95_low",
            "final_tail_eval_margin_diff_ci95_high",
        ),
        macro(
            "EelevenLongTailPracticalTrainingTailAccuracyDiff",
            fmt(practical_training["mean_final_tail_eval_accuracy_diff_muon_minus_adam"]),
        ),
        *ci_macros(
            "EelevenLongTailPracticalTrainingTailAccuracyDiff",
            practical_training,
            "final_tail_eval_accuracy_diff_ci95_low",
            "final_tail_eval_accuracy_diff_ci95_high",
        ),
        "",
        "% Long-tailed practical training LR sensitivity",
        macro("EelevenLongTailPracticalTrainingLrSweepSmallTrainLossRatio", fmt(lr_0003["geomean_final_train_loss_ratio_muon_over_adam"])),
        macro("EelevenLongTailPracticalTrainingLrSweepMediumTrainLossRatio", fmt(lr_001["geomean_final_train_loss_ratio_muon_over_adam"])),
        macro("EelevenLongTailPracticalTrainingLrSweepLargeTailLossRatio", fmt(lr_01["geomean_final_tail_eval_loss_ratio_muon_over_adam"])),
        macro("EelevenLongTailPracticalTrainingLrSweepLargeTailDriftRmsRatio", fmt(lr_01["geomean_final_tail_eval_drift_rms_ratio_muon_over_adam"])),
        "",
        "% Eight-step head-only forgetting diagnostic",
        macro("EelevenLongTailForgettingSteps", int(forgetting["head_only_steps"])),
        macro(
            "EelevenLongTailForgettingFinalDriftRatio",
            fmt(forgetting["geomean_final_tail_output_drift_sq_ratio_spectral_over_fro"]),
        ),
        *ci_macros(
            "EelevenLongTailForgettingFinalDriftRatio",
            forgetting,
            "final_tail_output_drift_sq_ratio_ci95_low",
            "final_tail_output_drift_sq_ratio_ci95_high",
        ),
        macro(
            "EelevenLongTailForgettingAreaDriftRatio",
            fmt(forgetting["geomean_tail_output_drift_area_ratio_spectral_over_fro"]),
        ),
        *ci_macros(
            "EelevenLongTailForgettingAreaDriftRatio",
            forgetting,
            "tail_output_drift_area_ratio_ci95_low",
            "tail_output_drift_area_ratio_ci95_high",
        ),
        macro(
            "EelevenLongTailForgettingFinalTailLossDiff",
            fmt(forgetting["mean_final_tail_loss_increase_diff_spectral_minus_fro"]),
        ),
        *ci_macros(
            "EelevenLongTailForgettingFinalTailLossDiff",
            forgetting,
            "final_tail_loss_increase_diff_ci95_low",
            "final_tail_loss_increase_diff_ci95_high",
        ),
        macro(
            "EelevenLongTailForgettingFinalTailMarginDropDiff",
            fmt(forgetting["mean_final_tail_margin_drop_diff_spectral_minus_fro"]),
        ),
        *ci_macros(
            "EelevenLongTailForgettingFinalTailMarginDropDiff",
            forgetting,
            "final_tail_margin_drop_diff_ci95_low",
            "final_tail_margin_drop_diff_ci95_high",
        ),
        "",
        "% Layerwise mechanism diagnostic",
        macro("EelevenLayerOneUnitJvpDriftRatio", fmt(layer_one["geomean_jvp_tail_drift_sq_ratio_spectral_over_fro"])),
        *ci_macros(
            "EelevenLayerOneUnitJvpDriftRatio",
            layer_one,
            "jvp_tail_drift_sq_ratio_ci95_low",
            "jvp_tail_drift_sq_ratio_ci95_high",
        ),
        macro("EelevenLayerOneScaledJvpDriftRatio", fmt(layer_one["geomean_scaled_jvp_tail_drift_sq_ratio_spectral_over_fro"])),
        *ci_macros(
            "EelevenLayerOneScaledJvpDriftRatio",
            layer_one,
            "scaled_jvp_tail_drift_sq_ratio_ci95_low",
            "scaled_jvp_tail_drift_sq_ratio_ci95_high",
        ),
        macro("EelevenLayerOneObservedDriftRatio", fmt(layer_one["geomean_observed_tail_drift_sq_ratio_spectral_over_fro"])),
        *ci_macros(
            "EelevenLayerOneObservedDriftRatio",
            layer_one,
            "observed_tail_drift_sq_ratio_ci95_low",
            "observed_tail_drift_sq_ratio_ci95_high",
        ),
        macro("EelevenLayerTwoUnitJvpDriftRatio", fmt(layer_two["geomean_jvp_tail_drift_sq_ratio_spectral_over_fro"])),
        *ci_macros(
            "EelevenLayerTwoUnitJvpDriftRatio",
            layer_two,
            "jvp_tail_drift_sq_ratio_ci95_low",
            "jvp_tail_drift_sq_ratio_ci95_high",
        ),
        macro("EelevenLayerTwoScaledJvpDriftRatio", fmt(layer_two["geomean_scaled_jvp_tail_drift_sq_ratio_spectral_over_fro"])),
        *ci_macros(
            "EelevenLayerTwoScaledJvpDriftRatio",
            layer_two,
            "scaled_jvp_tail_drift_sq_ratio_ci95_low",
            "scaled_jvp_tail_drift_sq_ratio_ci95_high",
        ),
        macro("EelevenLayerTwoObservedDriftRatio", fmt(layer_two["geomean_observed_tail_drift_sq_ratio_spectral_over_fro"])),
        *ci_macros(
            "EelevenLayerTwoObservedDriftRatio",
            layer_two,
            "observed_tail_drift_sq_ratio_ci95_low",
            "observed_tail_drift_sq_ratio_ci95_high",
        ),
        "",
    ]

    text = "\n".join(lines)
    for output_path in (DISCUSSION_OUTPUT_PATH, PAPER_OUTPUT_PATH):
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(text, encoding="utf-8")
    print(f"saved paper numbers to {DISCUSSION_OUTPUT_PATH} and {PAPER_OUTPUT_PATH}")


if __name__ == "__main__":
    main()
