from __future__ import annotations

from pathlib import Path
import sys

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from e11_condition_geometry.statistics import ci95


SUMMARY_PATH = Path("results/e11_local_linearization/summary.csv")
TABLE_PATH = Path("paper/specgrad_activation_paper/tables/local_linearization_errors.tex")
SOURCE_PATH = Path("results/e11_long_tail_muon_bridge/step_metrics.csv")

DISPLAY_NAMES = {
    "frobenius_grad": "Fro/GD",
    "polar_grad": r"$\polar(G_t)$",
    "polar_momentum": r"$\polar(M_t)$",
    "ns_momentum": r"NS$(M_t)$",
}
ORDER = ["frobenius_grad", "polar_grad", "polar_momentum", "ns_momentum"]


def fmt(value: float) -> str:
    value = float(value)
    if abs(value) >= 100 or (abs(value) < 1e-3 and value != 0.0):
        return f"{value:.2e}"
    return f"{value:.4g}"


def ci_text(mean: float, low: float, high: float) -> str:
    return f"{fmt(mean)} [{fmt(low)}, {fmt(high)}]"


def build_summary() -> pd.DataFrame:
    source = pd.read_csv(SOURCE_PATH)
    required = {
        "direction",
        "tail_output_jvp_fro",
        "tail_output_linearization_residual_fro",
        "tail_output_linearization_relative_error",
    }
    missing = sorted(required - set(source.columns))
    if missing:
        raise ValueError(f"{SOURCE_PATH} missing local linearization columns: {missing}")

    rows = []
    for direction in ORDER:
        group = source[source["direction"].eq(direction)]
        if group.empty:
            raise ValueError(f"missing direction {direction} in {SOURCE_PATH}")
        rel_mean, rel_low, rel_high = ci95(group["tail_output_linearization_relative_error"])
        jvp_mean, jvp_low, jvp_high = ci95(group["tail_output_jvp_fro"])
        residual_mean, residual_low, residual_high = ci95(group["tail_output_linearization_residual_fro"])
        rows.append(
            {
                "direction": direction,
                "display_name": DISPLAY_NAMES[direction],
                "seeds": int(group["seed"].nunique()),
                "mean_relative_error": rel_mean,
                "relative_error_ci95_low": rel_low,
                "relative_error_ci95_high": rel_high,
                "mean_jvp_fro": jvp_mean,
                "jvp_fro_ci95_low": jvp_low,
                "jvp_fro_ci95_high": jvp_high,
                "mean_residual_fro": residual_mean,
                "residual_fro_ci95_low": residual_low,
                "residual_fro_ci95_high": residual_high,
            }
        )
    return pd.DataFrame(rows)


def write_table(summary: pd.DataFrame) -> None:
    lines = [
        "% Auto-generated by scripts/e11_write_local_linearization_table.py. Do not edit by hand.",
        r"\begin{table}[H]",
        r"\centering",
        r"\caption{Local linearization error for the controlled long-tailed digits fixed-checkpoint diagnostic. The relative error is $\norm{F_T(\theta+\Delta)-F_T(\theta)-J_T\Delta}/\norm{J_T\Delta}$ after matched-head-gain scaling.}",
        r"\label{tab:local-linearization-error}",
        r"\footnotesize",
        r"\begin{tabular}{@{}lccc@{}}",
        r"\toprule",
        r"Direction & Relative error & $\norm{J_T\Delta}_F$ & Residual norm \\",
        r"\midrule",
    ]
    for row in summary.itertuples(index=False):
        lines.append(
            f"{row.display_name} & "
            f"{ci_text(row.mean_relative_error, row.relative_error_ci95_low, row.relative_error_ci95_high)} & "
            f"{ci_text(row.mean_jvp_fro, row.jvp_fro_ci95_low, row.jvp_fro_ci95_high)} & "
            f"{ci_text(row.mean_residual_fro, row.residual_fro_ci95_low, row.residual_fro_ci95_high)} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}"])
    TABLE_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    SUMMARY_PATH.parent.mkdir(parents=True, exist_ok=True)
    summary = build_summary()
    summary.to_csv(SUMMARY_PATH, index=False)
    write_table(summary)
    print(f"wrote {SUMMARY_PATH}")
    print(f"wrote {TABLE_PATH}")
    print(summary.to_string(index=False))


if __name__ == "__main__":
    main()
