from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from e11_condition_geometry.paper_stats import load_paper_stats
from e11_condition_geometry.reporting import fmt, ratio_ci


OUTPUT_PATH = Path("discussion/e11_paper_numbers.tex")


def macro(name: str, value: object) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}"


def latex_text(value: object) -> str:
    return str(value).replace("_", "\\_")


def ci_macros(prefix: str, record: object) -> list[str]:
    return [
        macro(f"{prefix}CiLow", fmt(record["ratio_ci95_low"])),
        macro(f"{prefix}CiHigh", fmt(record["ratio_ci95_high"])),
        macro(f"{prefix}Ci", ratio_ci(record)),
    ]


def main() -> None:
    stats = load_paper_stats()

    lines = [
        "% Auto-generated by scripts/e11_write_paper_numbers.py.",
        "% Do not edit by hand; regenerate after updating results.",
        "",
        "% C1: update-spectrum signature",
        macro("EelevenNrUpdateRatio", fmt(stats.nr_update["geomean_ratio_muon_over_adam"])),
        *ci_macros("EelevenNrUpdateRatio", stats.nr_update),
        macro("EelevenStUpdateRatio", fmt(stats.st_update["geomean_ratio_muon_over_adam"])),
        *ci_macros("EelevenStUpdateRatio", stats.st_update),
        "",
        "% C2: one-step calibration",
        macro("EelevenFirstOrderSpearman", fmt(stats.calibration_all["spearman_delta_vs_first_order"])),
        macro("EelevenFirstOrderSpearmanCiLow", fmt(stats.calibration_all["spearman_ci95_low"])),
        macro("EelevenFirstOrderSpearmanCiHigh", fmt(stats.calibration_all["spearman_ci95_high"])),
        macro(
            "EelevenFirstOrderSpearmanCi",
            f"[{fmt(stats.calibration_all['spearman_ci95_low'])}, "
            f"{fmt(stats.calibration_all['spearman_ci95_high'])}]",
        ),
        macro("EelevenFirstOrderWithinFactorTwo", fmt(stats.calibration_all["within_factor_2"])),
        "",
        "% C3: norm-geometry boundary",
        macro("EelevenFroFlatOverGdRatio", fmt(stats.spectral_fro["geomean_ratio"])),
        *ci_macros("EelevenFroFlatOverGdRatio", stats.spectral_fro),
        macro("EelevenOpFlatOverGdRatio", fmt(stats.spectral_op["geomean_ratio"])),
        *ci_macros("EelevenOpFlatOverGdRatio", stats.spectral_op),
        "",
        "% C4: mechanism boundary map",
        macro("EelevenBoundaryMuonFlatFavorableRows", stats.boundary_counts.muon_flat_favorable),
        macro("EelevenBoundaryOwnUpdatePositiveControlRows", stats.boundary_counts.own_update_positive_control),
        macro("EelevenBoundaryFavorableRows", stats.boundary_counts.favorable),
        macro("EelevenBoundaryUnfavorableRows", stats.boundary_counts.unfavorable),
        macro("EelevenBoundaryMixedRows", stats.boundary_counts.mixed),
        "",
        "% C5: neural MNIST sanity checks",
        macro("EelevenDeepMnistNrUpdateRatio", fmt(stats.deep_nr["geomean_ratio_muon_over_adam"])),
        *ci_macros("EelevenDeepMnistNrUpdateRatio", stats.deep_nr),
        macro("EelevenDeepMnistStUpdateRatio", fmt(stats.deep_st["geomean_ratio_muon_over_adam"])),
        *ci_macros("EelevenDeepMnistStUpdateRatio", stats.deep_st),
        macro("EelevenDeepMnistFirstOrderRatio", fmt(stats.deep_first["geomean_ratio_muon_over_adam"])),
        *ci_macros("EelevenDeepMnistFirstOrderRatio", stats.deep_first),
        macro("EelevenPatchMnistNrUpdateRatio", fmt(stats.patch_nr["geomean_ratio_muon_over_adam"])),
        *ci_macros("EelevenPatchMnistNrUpdateRatio", stats.patch_nr),
        macro("EelevenPatchMnistStUpdateRatio", fmt(stats.patch_st["geomean_ratio_muon_over_adam"])),
        *ci_macros("EelevenPatchMnistStUpdateRatio", stats.patch_st),
        macro("EelevenPatchMnistFirstOrderRatio", fmt(stats.patch_first["geomean_ratio_muon_over_adam"])),
        *ci_macros("EelevenPatchMnistFirstOrderRatio", stats.patch_first),
        macro("EelevenConvMnistNrUpdateRatio", fmt(stats.conv_nr["geomean_ratio_muon_over_adam"])),
        *ci_macros("EelevenConvMnistNrUpdateRatio", stats.conv_nr),
        macro("EelevenConvMnistStUpdateRatio", fmt(stats.conv_st["geomean_ratio_muon_over_adam"])),
        *ci_macros("EelevenConvMnistStUpdateRatio", stats.conv_st),
        macro("EelevenConvMnistFirstOrderRatio", fmt(stats.conv_first["geomean_ratio_muon_over_adam"])),
        *ci_macros("EelevenConvMnistFirstOrderRatio", stats.conv_first),
        "",
        "% C6: stateless trajectory mechanism control",
        macro("EelevenStatelessMeanNrUpdateRatio", fmt(stats.stateless_traj_nr["geomean_ratio"])),
        *ci_macros("EelevenStatelessMeanNrUpdateRatio", stats.stateless_traj_nr),
        macro("EelevenStatelessTotalDecreaseRatio", fmt(stats.stateless_traj_decrease["geomean_ratio"])),
        *ci_macros("EelevenStatelessTotalDecreaseRatio", stats.stateless_traj_decrease),
        "",
        "% C7: predictive-boundary gap",
        macro("EelevenBoundaryPredictorBestBalancedAccuracy", fmt(stats.predictor_best["mean_balanced_accuracy"])),
        macro("EelevenBoundaryPredictorBestFeatureSet", latex_text(stats.predictor_best["feature_set"])),
        macro(
            "EelevenBoundaryPredictorChanceFilledBalancedAccuracy",
            fmt(stats.predictor_uncertainty_best["mean_balanced_accuracy_chance_filled"]),
        ),
        macro("EelevenBoundaryPredictorChanceFilledCiLow", fmt(stats.predictor_uncertainty_best["balanced_accuracy_ci95_low"])),
        macro("EelevenBoundaryPredictorChanceFilledCiHigh", fmt(stats.predictor_uncertainty_best["balanced_accuracy_ci95_high"])),
        macro(
            "EelevenBoundaryPredictorChanceFilledCi",
            f"[{fmt(stats.predictor_uncertainty_best['balanced_accuracy_ci95_low'])}, "
            f"{fmt(stats.predictor_uncertainty_best['balanced_accuracy_ci95_high'])}]",
        ),
        "",
    ]

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"saved paper numbers to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
